### ISSUE TITLE
Unavailable plaform version

### ISSUE THREAD

**Issue by fbukevin** [awsdocs/aws-elastic-beanstalk-developer-guide#11]
In [php-hawordpress-tutorial.md](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/php-hawordpress-tutorial.md#launch-an-elastic-beanstalk-environment), the version choice is no longer available:

```
Choose Change platform configuration and select 64bit Amazon Linux 2016.09 v2.3.1 running PHP 5.6 from the drop down menu and then choose Save. 
```

This is the available platform versions on 2018/03/15 10:57 UTC.
![2018-03-15 18 54 05](https://user-images.githubusercontent.com/4548874/37459234-6b81016e-2882-11e8-89c0-5edf2934d1c4.png)

**Comment by dankhen** [comment]
Thanks @fbukevin.
I am looking into it.

**Comment by dankhen** [comment]
So the reason we had this instruction is that the tutorial was originally developed for PHP 5, and we haven't tested it with PHP 7 yet. We will do so. If it works w/o an issue, or we can easily make it work, we will remove this step altogether and have customers run the latest PHP configuration. If we must require PHP 5, we will change the requirement to "latest PHP 5.6 configuration version", so that it doesn't go out of date.

Thanks very much for reporting this!
