### ISSUE TITLE
ERROR: InvalidParameterValueError - Each option setting in configuration file must be a map

### ISSUE THREAD

**Issue by fbukevin** [awsdocs/aws-elastic-beanstalk-developer-guide#93]
The **node-express/.ebextensions/nodecommand.config** in this [page](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/create_deploy_nodejs_express.md#update-the-application) is not work.

```yaml
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"
```

Here is my test result:
```shell
$ eb deploy stage -m 'stage: test1'
Creating application version archive "app-2a64-200707_032203".
Uploading test-app/app-2a64-200707_032203.zip to S3. This may take a while.
Upload Complete.
ERROR: InvalidParameterValueError - Each option setting in configuration file .ebextensions/nodecommand.config in application version app-2a64-200707_032203 must be a map. Update each option setting in the configuration file.

$ cat .ebextensions/nodecommand.config
option_settings:
  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "npm start"
```

**Comment by dankhen** [comment]
@fbukevin This is due to the update to Amazon Linux 2 (AL2) platforms. Unfortunately we haven't had a chance to go over all tutorials and examples and update them. We're tracking this issue, and we apologize for the time it's taking.

We did, however, update the main topics for each platform, and there's a migration topic that explains the difference between the legacy and new platforms.

For Node.js platform, see [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs.container.html) and the sub-topics under it.
For migration, see [here](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.migration-al.html) - please expand the Node.js collapsed section.

**Comment by fbukevin** [comment]
@dankhen Thanks for your prompt response. I understood. I solved this problem by replacing the **.ebextensions/nodecommand.config** with a **Procfile** as mentioned in document.

```
web: node index.js
```

I originally thought that my instance is still using Amazon Linux (Version 1). Because when I check out the EC2 instance list. The instance is not marked as using Amazon Linux 2. That makes me misunderstood. Now I confirmed the issue.
